### ISSUE TITLE
TypeScript declaration

### ISSUE THREAD

**Issue by gfazioli** [golmansax/thum.io-js#1]
Hi and thank you for the package 👍 

Would be great to publish the types as well in order to use the package in TypeScript as well.

WDYT?

**Comment by golmansax** [comment]
@gfazioli Yes, that is a great idea!  If you have the capacity, we're definitely open to a PR.

Otherwise, will keep you posted on when we free up time to work on it.

**Comment by golmansax** [comment]
@gfazioli TypeScript definitions have been added in release v1.09 (https://github.com/golmansax/thum.io-js/releases/tag/v1.0.9).

Give them a shot and let us know how it goes!
